# Generated by Django 4.2.1 on 2023-06-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_category_code_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(upload_to='images/tickets/'),
        ),
    ]
